Fix: EventMap.tsx style error
The error `src/components/EventMap.tsx(345,14): error TS2322: Type '{ children: string; jsx: true; }' is not assignable to type 'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'. Property 'jsx' does not exist on type 'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'` indicates an issue with how the `<style>` tag is being used. This commit will correct the usage of the style tag within the EventMap component.